# =============================================================================
# Claude Code Configuration Template
# =============================================================================
# Diese Datei gehört in: .claude/claude.yaml (oder CLAUDE.md im Projekt-Root)
#
# Zweck: Claude Code versteht dein Projekt und kann autonom arbeiten.
# Je besser diese Datei gepflegt ist, desto weniger Rückfragen stellt Claude.
# =============================================================================

# -----------------------------------------------------------------------------
# PROJEKT-METADATEN
# -----------------------------------------------------------------------------
# Grundlegende Informationen über dein Projekt
project:
  # Name des Projekts (wird in Claude's Kontext verwendet)
  name: "Mein Projekt"
  
  # Projekttyp - hilft Claude die richtigen Konventionen anzuwenden
  # Beispiele: ansible, python, bash, terraform, kubernetes, docker, nodejs
  type: "ansible"
  
  # Kurze Beschreibung - Claude nutzt diese für Kontext
  description: "Beschreibung was dieses Projekt macht"
  
  # Optional: Versionierung
  version: "1.0.0"
  
  # Optional: Zielplattformen
  platforms:
    - "Rocky Linux 8"
    - "Rocky Linux 9"

# -----------------------------------------------------------------------------
# VERZEICHNISSTRUKTUR
# -----------------------------------------------------------------------------
# Erkläre Claude wo sich was befindet
# Ohne diese Info muss Claude raten oder nachfragen
structure:
  # Ansible-spezifische Pfade
  roles_dir: "roles/"
  defaults: "defaults/main.yml"
  tasks: "tasks/"
  handlers: "handlers/"
  templates: "templates/"
  files: "files/"
  vars: "vars/"
  meta: "meta/"
  
  # Allgemeine Pfade (für andere Projekttypen)
  # src: "src/"
  # tests: "tests/"
  # docs: "docs/"
  # config: "config/"
  # scripts: "scripts/"

# -----------------------------------------------------------------------------
# KONVENTIONEN
# -----------------------------------------------------------------------------
# Regeln die Claude beim Bearbeiten von Code befolgen soll
# Je spezifischer, desto konsistenter der Output
conventions:
  # Namenskonventionen
  - "Task-Namen beginnen mit [Modulname] in eckigen Klammern"
  - "Variablen-Präfix: projektname_"
  - "Handler-Namen: restart_servicename"
  
  # Code-Stil
  - "Alle Tasks müssen idempotent sein"
  - "Keine shell/command wenn ein Modul existiert"
  - "FQCN (Fully Qualified Collection Names) verwenden"
  
  # Dokumentation
  - "Jede neue Variable muss in defaults/main.yml dokumentiert werden"
  - "Komplexe Logik braucht Inline-Kommentare"
  
  # Struktur
  - "Jedes Feature bekommt eine eigene Task-Datei"
  - "Zugehörige Audit-Tasks in separater Datei"
  - "Keine Logik in main.yml - nur includes"

# -----------------------------------------------------------------------------
# TAGS
# -----------------------------------------------------------------------------
# Gruppierung von Tags für schnellen Überblick
# Claude nutzt diese um verwandte Tasks zu identifizieren
tags:
  # Gruppierte Tags
  hardening:
    - selinux
    - firewall
    - umask
    - mounts
    - dnf
  audit:
    - audit_selinux
    - audit_firewall
  
  # Oder flache Liste
  # all_tags:
  #   - install
  #   - configure
  #   - deploy
  #   - test

# -----------------------------------------------------------------------------
# BEFEHLE
# -----------------------------------------------------------------------------
# Häufig verwendete Befehle - Claude kann diese direkt ausführen
commands:
  # Ansible-spezifisch
  full_run: "ansible-playbook playbook.yml"
  check_mode: "ansible-playbook playbook.yml --check --diff"
  syntax_check: "ansible-playbook playbook.yml --syntax-check"
  lint: "ansible-lint ."
  
  # Allgemein nützlich
  # test: "pytest tests/"
  # build: "make build"
  # deploy: "make deploy"
  # clean: "make clean"

# -----------------------------------------------------------------------------
# BERECHTIGUNGEN (WICHTIG!)
# -----------------------------------------------------------------------------
# Steuert was Claude ohne Rückfrage tun darf
# Das ist der Schlüssel für autonomes Arbeiten
permissions:
  # Diese Aktionen darf Claude sofort ausführen
  allow_without_confirmation:
    - edit_tasks           # Task-Dateien bearbeiten
    - edit_defaults        # Default-Variablen ändern
    - edit_handlers        # Handler bearbeiten
    - edit_templates       # Jinja2-Templates ändern
    - edit_readme          # Dokumentation aktualisieren
    - create_new_modules   # Neue Module/Dateien erstellen
    - run_syntax_check     # Syntax prüfen
    - run_lint             # Linting ausführen
    - run_tests            # Tests ausführen
    - git_add              # Dateien stagen
    - git_commit           # Commits erstellen
  
  # Diese Aktionen erfordern explizite Bestätigung
  require_confirmation:
    - run_playbook_on_hosts   # Playbooks auf echten Hosts ausführen
    - delete_files            # Dateien löschen
    - modify_inventory        # Inventory ändern
    - git_push                # Zum Remote pushen
    - deploy_production       # Produktions-Deployments

# -----------------------------------------------------------------------------
# MODUL-TEMPLATE
# -----------------------------------------------------------------------------
# Vorlagen für neue Module - Claude nutzt diese beim Erstellen
module_template:
  # Dateinamen-Muster (Platzhalter: {module_name})
  task_file_pattern: "tasks/{module_name}.yml"
  audit_file_pattern: "tasks/audit_{module_name}.yml"
  handler_file_pattern: "handlers/{module_name}.yml"
  
  # Diese Tags müssen neue Module haben
  required_tags:
    task: ["hardening", "{module_name}"]
    audit: ["audit", "audit_{module_name}"]
  
  # Diese Variablen müssen definiert werden
  required_variables:
    - "enable_{module_name}_hardening"
    - "enable_{module_name}_audit"
  
  # Optional: Boilerplate für neue Task-Dateien
  # task_template: |
  #   ---
  #   # {module_name} Tasks
  #   - name: "[{module_name}] Beschreibung"
  #     ansible.builtin.debug:
  #       msg: "TODO: Implementieren"
  #     tags:
  #       - hardening
  #       - {module_name}

# -----------------------------------------------------------------------------
# CODE-STIL
# -----------------------------------------------------------------------------
# Formatierungsregeln für konsistenten Output
style:
  yaml:
    indent: 2              # Einrückung
    line_length: 120       # Maximale Zeilenlänge
    quote_style: double    # "double" oder 'single'
    flow_style: false      # Kompakte Schreibweise vermeiden
  
  ansible:
    fqcn: true             # ansible.builtin.file statt file
    name_prefix: true      # [Modul] vor Task-Namen
    block_style: true      # block/rescue/always verwenden
    
  # Für Python-Projekte
  # python:
  #   formatter: black
  #   line_length: 88
  #   docstring_style: google

# -----------------------------------------------------------------------------
# VALIDIERUNG
# -----------------------------------------------------------------------------
# Prüfungen die Claude vor/nach Änderungen ausführen soll
validation:
  # Vor dem Commit
  pre_commit:
    - "ansible-lint ."
    - "ansible-playbook playbook.yml --syntax-check"
    - "yamllint ."
  
  # Nach Änderungen an bestimmten Dateien
  on_change:
    "*.yml":
      - "yamllint {file}"
    "tasks/*.yml":
      - "ansible-lint {file}"
  
  # Optional: CI-Befehle
  # ci:
  #   - "molecule test"

# -----------------------------------------------------------------------------
# DOKUMENTATION
# -----------------------------------------------------------------------------
# Regeln für automatische Dokumentationspflege
documentation:
  # Haupt-Dokumentation
  readme: "README.md"
  changelog: "CHANGELOG.md"
  
  # Wann README aktualisieren?
  update_readme_on:
    - new_module      # Neues Modul erstellt
    - new_variable    # Neue Variable in defaults
    - tag_changes     # Tags geändert
    - api_changes     # Breaking Changes
  
  # Welche Abschnitte muss README haben?
  required_sections:
    - features
    - installation
    - configuration
    - usage
    - examples
    - tags

# -----------------------------------------------------------------------------
# TESTING
# -----------------------------------------------------------------------------
# Test-Framework Konfiguration
testing:
  # Molecule für Ansible
  molecule:
    driver: docker
    platforms:
      - rockylinux:8
      - rockylinux:9
    scenarios:
      - default
      - hardening_only
      - audit_only
  
  # Test-Befehle
  test_commands:
    unit: "molecule test"
    converge: "molecule converge"
    verify: "molecule verify"
    destroy: "molecule destroy"
    lint: "molecule lint"
  
  # Für Python
  # pytest:
  #   config: "pytest.ini"
  #   markers:
  #     - unit
  #     - integration
  #     - slow

# -----------------------------------------------------------------------------
# ABHÄNGIGKEITEN
# -----------------------------------------------------------------------------
# Was braucht dieses Projekt?
dependencies:
  # Ansible Collections
  collections:
    - community.general
    - ansible.posix
  
  # Python-Pakete
  python:
    - ansible-core>=2.9
    - ansible-lint
    - yamllint
    - molecule
    - molecule-docker
  
  # System-Pakete
  # system:
  #   - docker
  #   - git

# -----------------------------------------------------------------------------
# UMGEBUNGSVARIABLEN
# -----------------------------------------------------------------------------
# Bekannte/benötigte Umgebungsvariablen
# environment:
#   required:
#     - ANSIBLE_VAULT_PASSWORD_FILE
#   optional:
#     - ANSIBLE_STDOUT_CALLBACK

# -----------------------------------------------------------------------------
# SECRETS
# -----------------------------------------------------------------------------
# Hinweise zum Umgang mit Secrets (Claude sieht diese nie)
# secrets:
#   vault_files:
#     - "vars/vault.yml"
#   never_commit:
#     - "*.vault"
#     - "secrets/"
#     - ".env"

# -----------------------------------------------------------------------------
# GIT-WORKFLOW
# -----------------------------------------------------------------------------
# Wie soll Claude mit Git umgehen?
# git:
#   branch_naming: "feature/{description}"
#   commit_style: "conventional"  # feat:, fix:, docs:, etc.
#   auto_commit: false           # Automatisch committen?

# -----------------------------------------------------------------------------
# CUSTOM RULES
# -----------------------------------------------------------------------------
# Projektspezifische Regeln die nirgendwo anders passen
# custom:
#   - "Firewall-Tasks immer mit rescue-Block"
#   - "SELinux-Änderungen erfordern Reboot-Handler"
#   - "Alle Passwörter via Vault"